run:
  timeout: 5m
  build-tags:
    - noui

linters:
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - gofmt
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - revive
    - staticcheck
    - unused
    - wastedassign

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
