/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InfraRouteImport } from './routes/infra'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposSlugRouteImport } from './routes/repos.$slug'
import { Route as ReposSlugEnvsEnvIdRouteImport } from './routes/repos.$slug.envs.$envId'

const InfraRoute = InfraRouteImport.update({
  id: '/infra',
  path: '/infra',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposSlugRoute = ReposSlugRouteImport.update({
  id: '/repos/$slug',
  path: '/repos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposSlugEnvsEnvIdRoute = ReposSlugEnvsEnvIdRouteImport.update({
  id: '/envs/$envId',
  path: '/envs/$envId',
  getParentRoute: () => ReposSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/infra': typeof InfraRoute
  '/repos/$slug': typeof ReposSlugRouteWithChildren
  '/repos/$slug/envs/$envId': typeof ReposSlugEnvsEnvIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/infra': typeof InfraRoute
  '/repos/$slug': typeof ReposSlugRouteWithChildren
  '/repos/$slug/envs/$envId': typeof ReposSlugEnvsEnvIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/infra': typeof InfraRoute
  '/repos/$slug': typeof ReposSlugRouteWithChildren
  '/repos/$slug/envs/$envId': typeof ReposSlugEnvsEnvIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/infra' | '/repos/$slug' | '/repos/$slug/envs/$envId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/infra' | '/repos/$slug' | '/repos/$slug/envs/$envId'
  id: '__root__' | '/' | '/infra' | '/repos/$slug' | '/repos/$slug/envs/$envId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfraRoute: typeof InfraRoute
  ReposSlugRoute: typeof ReposSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/infra': {
      id: '/infra'
      path: '/infra'
      fullPath: '/infra'
      preLoaderRoute: typeof InfraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$slug': {
      id: '/repos/$slug'
      path: '/repos/$slug'
      fullPath: '/repos/$slug'
      preLoaderRoute: typeof ReposSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$slug/envs/$envId': {
      id: '/repos/$slug/envs/$envId'
      path: '/envs/$envId'
      fullPath: '/repos/$slug/envs/$envId'
      preLoaderRoute: typeof ReposSlugEnvsEnvIdRouteImport
      parentRoute: typeof ReposSlugRoute
    }
  }
}

interface ReposSlugRouteChildren {
  ReposSlugEnvsEnvIdRoute: typeof ReposSlugEnvsEnvIdRoute
}

const ReposSlugRouteChildren: ReposSlugRouteChildren = {
  ReposSlugEnvsEnvIdRoute: ReposSlugEnvsEnvIdRoute,
}

const ReposSlugRouteWithChildren = ReposSlugRoute._addFileChildren(
  ReposSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfraRoute: InfraRoute,
  ReposSlugRoute: ReposSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
