import type { Client } from "@libsql/client";
import { and, asc, desc, eq, ne, sql } from "drizzle-orm";
import { drizzle, type LibSQLDatabase } from "drizzle-orm/libsql";
import {
  BASELINE_DDL,
  clones,
  registeredRepos,
  repos,
  schema,
  type Schema,
  watchedPaths,
  worktrees,
} from "spawntree-core";
import type { Clone, RegisteredRepo, Repo, WatchedPath, Worktree } from "spawntree-core";

function nowIso() {
  return new Date().toISOString();
}

/**
 * Daemon-facing view of the spawntree catalog.
 *
 * Every read and write goes through a typed Drizzle query builder against
 * the libSQL client handed to it by the `StorageManager`. No raw SQL, no
 * `row["name"] as string` casts, no hand-rolled INSERT templates — all
 * the column names and row shapes come from the Drizzle schema in
 * `spawntree-core/db`, which is the same one external tools import when
 * they want to read the catalog directly.
 *
 * The client lifecycle belongs to the caller (the `StorageManager`);
 * `close()` on this class is a no-op so the same libSQL connection can
 * back concurrent consumers — the live catalog plus any replicators.
 */
export class CatalogDatabase {
  private readonly db: LibSQLDatabase<Schema>;

  private constructor(_client: Client, db: LibSQLDatabase<Schema>) {
    this.db = db;
  }

  /**
   * Open a catalog against an already-connected libSQL client. Applies the
   * baseline DDL idempotently so a fresh database comes up with the right
   * shape on first boot. Proper incremental migrations (generated by
   * `drizzle-kit generate` under `packages/core/src/db/migrations/`) are
   * on deck for when schema changes start shipping.
   */
  static async open(client: Client): Promise<CatalogDatabase> {
    for (const stmt of BASELINE_DDL) {
      await client.execute(stmt);
    }
    const db = drizzle(client, { schema });
    return new CatalogDatabase(client, db);
  }

  async close(): Promise<void> {
    // The libSQL client is owned by the StorageManager.
  }

  // ─── repos ─────────────────────────────────────────────────────────────

  async repoCount(): Promise<number> {
    const [row] = await this.db
      .select({ count: sql<number>`count(*)`.as("count") })
      .from(repos);
    return Number(row?.count ?? 0);
  }

  async upsertRepo(repo: Repo): Promise<void> {
    const registeredAt = repo.registeredAt || nowIso();
    const updatedAt = nowIso();
    await this.db.transaction(async (tx) => {
      // Clear any stale entry reusing this slug under a different id.
      await tx
        .delete(repos)
        .where(and(eq(repos.slug, repo.slug), ne(repos.id, repo.id)));
      await tx
        .insert(repos)
        .values({
          id: repo.id,
          slug: repo.slug,
          name: repo.name,
          provider: repo.provider,
          owner: repo.owner,
          remoteUrl: repo.remoteUrl ?? "",
          defaultBranch: repo.defaultBranch ?? "",
          description: repo.description ?? "",
          registeredAt,
          updatedAt,
        })
        .onConflictDoUpdate({
          target: repos.id,
          set: {
            slug: repo.slug,
            name: repo.name,
            provider: repo.provider,
            owner: repo.owner,
            remoteUrl: repo.remoteUrl ?? "",
            defaultBranch: repo.defaultBranch ?? "",
            description: repo.description ?? "",
            updatedAt,
          },
        });
    });
  }

  async listRepos(): Promise<Array<Repo>> {
    const rows = await this.db
      .select()
      .from(repos)
      .orderBy(desc(repos.updatedAt), asc(repos.name));
    return rows.map(toRepo);
  }

  async getRepo(id: string): Promise<Repo | undefined> {
    const [row] = await this.db
      .select()
      .from(repos)
      .where(eq(repos.id, id))
      .limit(1);
    return row ? toRepo(row) : undefined;
  }

  async getRepoBySlug(slug: string): Promise<Repo | undefined> {
    const [row] = await this.db
      .select()
      .from(repos)
      .where(eq(repos.slug, slug))
      .limit(1);
    return row ? toRepo(row) : undefined;
  }

  // ─── clones ────────────────────────────────────────────────────────────

  async upsertClone(clone: Clone): Promise<void> {
    const registeredAt = clone.registeredAt || nowIso();
    const lastSeenAt = nowIso();
    await this.db.transaction(async (tx) => {
      await tx
        .delete(clones)
        .where(and(eq(clones.path, clone.path), ne(clones.id, clone.id)));
      await tx
        .insert(clones)
        .values({
          id: clone.id,
          repoId: clone.repoId,
          path: clone.path,
          status: clone.status,
          lastSeenAt,
          registeredAt,
        })
        .onConflictDoUpdate({
          target: clones.id,
          set: {
            repoId: clone.repoId,
            path: clone.path,
            status: clone.status,
            lastSeenAt,
          },
        });
    });
  }

  async listClones(repoId: string): Promise<Array<Clone>> {
    const rows = await this.db
      .select()
      .from(clones)
      .where(eq(clones.repoId, repoId))
      .orderBy(asc(clones.registeredAt));
    return rows.map(toClone);
  }

  async getClone(cloneId: string): Promise<Clone | undefined> {
    const [row] = await this.db
      .select()
      .from(clones)
      .where(eq(clones.id, cloneId))
      .limit(1);
    return row ? toClone(row) : undefined;
  }

  async updateClonePath(cloneId: string, path: string): Promise<void> {
    await this.db
      .update(clones)
      .set({ path, status: "active", lastSeenAt: nowIso() })
      .where(eq(clones.id, cloneId));
  }

  async updateCloneStatus(cloneId: string, status: string): Promise<void> {
    await this.db
      .update(clones)
      .set({ status, lastSeenAt: nowIso() })
      .where(eq(clones.id, cloneId));
  }

  async deleteClone(cloneId: string): Promise<void> {
    await this.db.delete(clones).where(eq(clones.id, cloneId));
  }

  // ─── worktrees ─────────────────────────────────────────────────────────

  async replaceWorktrees(cloneId: string, entries: Array<Worktree>): Promise<void> {
    await this.db.transaction(async (tx) => {
      await tx.delete(worktrees).where(eq(worktrees.cloneId, cloneId));
      if (entries.length > 0) {
        await tx.insert(worktrees).values(
          entries.map((worktree) => ({
            path: worktree.path,
            cloneId,
            branch: worktree.branch,
            headRef: worktree.headRef,
            discoveredAt: worktree.discoveredAt,
          })),
        );
      }
    });
  }

  async listWorktrees(cloneId: string): Promise<Array<Worktree>> {
    const rows = await this.db
      .select()
      .from(worktrees)
      .where(eq(worktrees.cloneId, cloneId))
      .orderBy(asc(worktrees.path));
    return rows.map(toWorktree);
  }

  // ─── watched paths ─────────────────────────────────────────────────────

  async upsertWatchedPath(watchedPath: WatchedPath): Promise<void> {
    await this.db
      .insert(watchedPaths)
      .values({
        path: watchedPath.path,
        scanChildren: watchedPath.scanChildren ? 1 : 0,
        addedAt: watchedPath.addedAt || nowIso(),
        lastScannedAt: watchedPath.lastScannedAt ?? "",
        lastScanError: watchedPath.lastScanError ?? "",
      })
      .onConflictDoUpdate({
        target: watchedPaths.path,
        set: {
          scanChildren: watchedPath.scanChildren ? 1 : 0,
          lastScannedAt: watchedPath.lastScannedAt ?? "",
          lastScanError: watchedPath.lastScanError ?? "",
        },
      });
  }

  async listWatchedPaths(): Promise<Array<WatchedPath>> {
    const rows = await this.db
      .select()
      .from(watchedPaths)
      .orderBy(asc(watchedPaths.addedAt));
    return rows.map(toWatchedPath);
  }

  async updateWatchedPathScan(
    path: string,
    lastScannedAt: string,
    lastScanError = "",
  ): Promise<void> {
    await this.db
      .update(watchedPaths)
      .set({ lastScannedAt, lastScanError })
      .where(eq(watchedPaths.path, path));
  }

  // ─── registered repos ──────────────────────────────────────────────────

  async registerRepo(registered: RegisteredRepo): Promise<void> {
    await this.db
      .insert(registeredRepos)
      .values({
        repoId: registered.repoId,
        repoPath: registered.repoPath,
        configPath: registered.configPath,
        lastSeenAt: registered.lastSeenAt || nowIso(),
      })
      .onConflictDoUpdate({
        target: registeredRepos.repoId,
        set: {
          repoPath: registered.repoPath,
          configPath: registered.configPath,
          lastSeenAt: registered.lastSeenAt || nowIso(),
        },
      });
  }

  async listRegisteredRepos(): Promise<Array<RegisteredRepo>> {
    const rows = await this.db
      .select()
      .from(registeredRepos)
      .orderBy(desc(registeredRepos.lastSeenAt));
    return rows.map(toRegisteredRepo);
  }
}

// ─── row → domain mappers ────────────────────────────────────────────────
// Drizzle infers row shapes directly from the schema, so these are just
// renames (snake_case columns → camelCase domain fields) + a handful of
// null coalescing. No `as unknown as` casts.

function toRepo(row: typeof repos.$inferSelect): Repo {
  return {
    id: row.id,
    slug: row.slug as Repo["slug"],
    name: row.name,
    provider: row.provider,
    owner: row.owner,
    remoteUrl: row.remoteUrl,
    defaultBranch: row.defaultBranch,
    description: row.description,
    registeredAt: row.registeredAt,
    updatedAt: row.updatedAt,
  };
}

function toClone(row: typeof clones.$inferSelect): Clone {
  return {
    id: row.id as Clone["id"],
    repoId: row.repoId,
    path: row.path,
    status: row.status,
    lastSeenAt: row.lastSeenAt,
    registeredAt: row.registeredAt,
  };
}

function toWorktree(row: typeof worktrees.$inferSelect): Worktree {
  return {
    path: row.path,
    cloneId: row.cloneId as Worktree["cloneId"],
    branch: row.branch,
    headRef: row.headRef,
    discoveredAt: row.discoveredAt,
  };
}

function toWatchedPath(row: typeof watchedPaths.$inferSelect): WatchedPath {
  return {
    path: row.path,
    scanChildren: row.scanChildren === 1,
    addedAt: row.addedAt,
    lastScannedAt: row.lastScannedAt || undefined,
    lastScanError: row.lastScanError || undefined,
  };
}

function toRegisteredRepo(row: typeof registeredRepos.$inferSelect): RegisteredRepo {
  return {
    repoId: row.repoId as RegisteredRepo["repoId"],
    repoPath: row.repoPath,
    configPath: row.configPath,
    lastSeenAt: row.lastSeenAt,
  };
}
