import type { Client } from "@libsql/client";
import { and, eq, ne } from "drizzle-orm";
import {
  BASELINE_DDL,
  type CatalogDb,
  clones,
  registeredRepos,
  repos,
  watchedPaths,
  worktrees,
} from "spawntree-core";
import type { Clone, RegisteredRepo, Repo, WatchedPath, Worktree } from "spawntree-core";

/**
 * Apply the catalog baseline DDL to a libSQL client. Idempotent — safe to
 * call on every daemon boot. Used by `DaemonService.makeLayer()` right
 * after the storage primary is ready.
 *
 * Incremental migrations generated by `drizzle-kit generate` land here
 * once schema changes start shipping, layered on top of this baseline.
 */
export async function applyCatalogSchema(client: Client): Promise<void> {
  for (const stmt of BASELINE_DDL) {
    await client.execute(stmt);
  }
}

function nowIso() {
  return new Date().toISOString();
}

/**
 * Transactional upsert for `repos` that also evicts any stale row reusing
 * the same `slug` under a different `id`. The extra delete is what makes
 * this worth keeping as a helper — everything else in the catalog is a
 * single Drizzle call and lives inline in daemon-service.
 */
export async function upsertRepo(db: CatalogDb, repo: Repo): Promise<void> {
  const registeredAt = repo.registeredAt || nowIso();
  const updatedAt = nowIso();
  await db.transaction(async (tx) => {
    await tx.delete(repos).where(and(eq(repos.slug, repo.slug), ne(repos.id, repo.id)));
    await tx
      .insert(repos)
      .values({
        id: repo.id,
        slug: repo.slug,
        name: repo.name,
        provider: repo.provider,
        owner: repo.owner,
        remoteUrl: repo.remoteUrl ?? "",
        defaultBranch: repo.defaultBranch ?? "",
        description: repo.description ?? "",
        registeredAt,
        updatedAt,
      })
      .onConflictDoUpdate({
        target: repos.id,
        set: {
          slug: repo.slug,
          name: repo.name,
          provider: repo.provider,
          owner: repo.owner,
          remoteUrl: repo.remoteUrl ?? "",
          defaultBranch: repo.defaultBranch ?? "",
          description: repo.description ?? "",
          updatedAt,
        },
      });
  });
}

/**
 * Same shape as `upsertRepo` but for clones: evicts stale path collisions
 * under a different id before inserting.
 */
export async function upsertClone(db: CatalogDb, clone: Clone): Promise<void> {
  const registeredAt = clone.registeredAt || nowIso();
  const lastSeenAt = nowIso();
  await db.transaction(async (tx) => {
    await tx.delete(clones).where(and(eq(clones.path, clone.path), ne(clones.id, clone.id)));
    await tx
      .insert(clones)
      .values({
        id: clone.id,
        repoId: clone.repoId,
        path: clone.path,
        status: clone.status,
        lastSeenAt,
        registeredAt,
      })
      .onConflictDoUpdate({
        target: clones.id,
        set: {
          repoId: clone.repoId,
          path: clone.path,
          status: clone.status,
          lastSeenAt,
        },
      });
  });
}

/**
 * Replace the full set of worktrees for a clone in one transaction. Used
 * whenever we re-discover git worktrees on disk — the catalog's worktree
 * rows for that clone become exactly what we found.
 */
export async function replaceWorktrees(
  db: CatalogDb,
  cloneId: string,
  entries: Array<Worktree>,
): Promise<void> {
  await db.transaction(async (tx) => {
    await tx.delete(worktrees).where(eq(worktrees.cloneId, cloneId));
    if (entries.length > 0) {
      await tx.insert(worktrees).values(
        entries.map((worktree) => ({
          path: worktree.path,
          cloneId,
          branch: worktree.branch,
          headRef: worktree.headRef,
          discoveredAt: worktree.discoveredAt,
        })),
      );
    }
  });
}

/**
 * Idempotent insert for watched paths. One-liner, lives here so the
 * daemon can consistently go through the catalog module rather than
 * reaching into Drizzle schema internals.
 */
export async function upsertWatchedPath(db: CatalogDb, watchedPath: WatchedPath): Promise<void> {
  await db
    .insert(watchedPaths)
    .values({
      path: watchedPath.path,
      scanChildren: watchedPath.scanChildren ? 1 : 0,
      addedAt: watchedPath.addedAt || nowIso(),
      lastScannedAt: watchedPath.lastScannedAt ?? "",
      lastScanError: watchedPath.lastScanError ?? "",
    })
    .onConflictDoUpdate({
      target: watchedPaths.path,
      set: {
        scanChildren: watchedPath.scanChildren ? 1 : 0,
        lastScannedAt: watchedPath.lastScannedAt ?? "",
        lastScanError: watchedPath.lastScanError ?? "",
      },
    });
}

/** Same pattern for registered repos. */
export async function registerRepo(db: CatalogDb, registered: RegisteredRepo): Promise<void> {
  await db
    .insert(registeredRepos)
    .values({
      repoId: registered.repoId,
      repoPath: registered.repoPath,
      configPath: registered.configPath,
      lastSeenAt: registered.lastSeenAt || nowIso(),
    })
    .onConflictDoUpdate({
      target: registeredRepos.repoId,
      set: {
        repoPath: registered.repoPath,
        configPath: registered.configPath,
        lastSeenAt: registered.lastSeenAt || nowIso(),
      },
    });
}
