import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

/**
 * Spawntree catalog schema — the single source of truth for table shape
 * across the daemon (writer) and any external tool (reader).
 *
 * Every column is declared with its SQLite type AND Drizzle's TypeScript
 * type, so `db.select().from(repos)` returns a fully-typed row without any
 * `as` casts. External consumers import this schema, hand it to Drizzle
 * alongside a libSQL client, and query directly with the same types the
 * daemon uses internally.
 *
 * Philosophy: the schema is the API. Readers that connect via libSQL
 * (Turso sync, local file, S3-downloaded snapshot) don't need the daemon
 * HTTP to be running — they just need schema + a libSQL client. That lets
 * downstream integrations like cross-host dashboards, CLIs, and backup
 * verifiers avoid reimplementing read endpoints.
 */

export const repos = sqliteTable("repos", {
  id: text("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  provider: text("provider").notNull(),
  owner: text("owner").notNull().default(""),
  remoteUrl: text("remote_url").notNull().default(""),
  defaultBranch: text("default_branch").notNull().default(""),
  description: text("description").notNull().default(""),
  registeredAt: text("registered_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const clones = sqliteTable(
  "clones",
  {
    id: text("id").primaryKey(),
    repoId: text("repo_id")
      .notNull()
      .references(() => repos.id, { onDelete: "cascade" }),
    path: text("path").notNull().unique(),
    status: text("status").notNull().default("active"),
    lastSeenAt: text("last_seen_at").notNull(),
    registeredAt: text("registered_at").notNull(),
  },
  (table) => [index("clones_repo_id_idx").on(table.repoId)],
);

export const worktrees = sqliteTable(
  "worktrees",
  {
    path: text("path").primaryKey(),
    cloneId: text("clone_id")
      .notNull()
      .references(() => clones.id, { onDelete: "cascade" }),
    branch: text("branch").notNull().default(""),
    headRef: text("head_ref").notNull().default(""),
    discoveredAt: text("discovered_at").notNull(),
  },
  (table) => [index("worktrees_clone_id_idx").on(table.cloneId)],
);

export const watchedPaths = sqliteTable("watched_paths", {
  path: text("path").primaryKey(),
  // Boolean stored as 0/1. Drizzle's `{ mode: "boolean" }` would round-trip
  // to `true`/`false` but existing data uses integers — keep explicit.
  scanChildren: integer("scan_children").notNull().default(0),
  addedAt: text("added_at").notNull(),
  lastScannedAt: text("last_scanned_at").notNull().default(""),
  lastScanError: text("last_scan_error").notNull().default(""),
});

export const registeredRepos = sqliteTable("registered_repos", {
  repoId: text("repo_id").primaryKey(),
  repoPath: text("repo_path").notNull(),
  configPath: text("config_path").notNull(),
  lastSeenAt: text("last_seen_at").notNull(),
});

/**
 * Full schema object suitable for `drizzle(client, { schema })`. Clients
 * that want the relational query API (`db.query.repos.findMany(...)`)
 * pass this at connect time.
 */
export const schema = {
  repos,
  clones,
  worktrees,
  watchedPaths,
  registeredRepos,
};

export type Schema = typeof schema;

// Row type exports — handy for code that takes a catalog row as a param.
export type RepoRow = typeof repos.$inferSelect;
export type NewRepoRow = typeof repos.$inferInsert;
export type CloneRow = typeof clones.$inferSelect;
export type NewCloneRow = typeof clones.$inferInsert;
export type WorktreeRow = typeof worktrees.$inferSelect;
export type NewWorktreeRow = typeof worktrees.$inferInsert;
export type WatchedPathRow = typeof watchedPaths.$inferSelect;
export type NewWatchedPathRow = typeof watchedPaths.$inferInsert;
export type RegisteredRepoRow = typeof registeredRepos.$inferSelect;
export type NewRegisteredRepoRow = typeof registeredRepos.$inferInsert;

/**
 * DDL needed to bootstrap an empty database into the current schema.
 *
 * We keep this alongside the Drizzle schema so `CatalogDatabase.open(client)`
 * can bring any libSQL file to the right shape idempotently without
 * depending on `drizzle-kit migrate` at runtime. Proper incremental
 * migrations (generated by `drizzle-kit generate`) live under
 * `packages/core/src/db/migrations/` and apply on top of this baseline
 * once schema changes start shipping.
 *
 * Kept as individual statements because libSQL's `client.execute()` takes
 * one statement per call. Every statement is idempotent (`IF NOT EXISTS`).
 */
export const BASELINE_DDL: ReadonlyArray<string> = [
  "PRAGMA foreign_keys = ON",
  `CREATE TABLE IF NOT EXISTS repos (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    provider TEXT NOT NULL,
    owner TEXT NOT NULL DEFAULT '',
    remote_url TEXT NOT NULL DEFAULT '',
    default_branch TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    registered_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS clones (
    id TEXT PRIMARY KEY,
    repo_id TEXT NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
    path TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'active',
    last_seen_at TEXT NOT NULL,
    registered_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS clones_repo_id_idx ON clones(repo_id)`,
  `CREATE TABLE IF NOT EXISTS worktrees (
    path TEXT PRIMARY KEY,
    clone_id TEXT NOT NULL REFERENCES clones(id) ON DELETE CASCADE,
    branch TEXT NOT NULL DEFAULT '',
    head_ref TEXT NOT NULL DEFAULT '',
    discovered_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS worktrees_clone_id_idx ON worktrees(clone_id)`,
  `CREATE TABLE IF NOT EXISTS watched_paths (
    path TEXT PRIMARY KEY,
    scan_children INTEGER NOT NULL DEFAULT 0,
    added_at TEXT NOT NULL,
    last_scanned_at TEXT NOT NULL DEFAULT '',
    last_scan_error TEXT NOT NULL DEFAULT ''
  )`,
  `CREATE TABLE IF NOT EXISTS registered_repos (
    repo_id TEXT PRIMARY KEY,
    repo_path TEXT NOT NULL,
    config_path TEXT NOT NULL,
    last_seen_at TEXT NOT NULL
  )`,
];

// Re-export `sql` so external consumers can build raw clauses without a
// separate drizzle-orm import. `eq`, `and`, `or`, etc. can be imported from
// drizzle-orm by consumers who want them — we don't re-export the full
// query operator set to keep the public surface focused.
export { sql };
